"""
Minimal type stubs for OpenCV (cv2) used by TD_project image matching.
Runtime still requires `opencv-python` / `opencv-contrib-python` (with contrib for SIFT).
"""
from typing import Any, Dict, List, Optional, Tuple, Union

__version__: str

COLOR_BGR2GRAY: int

# --- I/O & display (recognition_control.py) ---
def imread(filename: str, flags: int = ...) -> Optional[Any]: ...
def cvtColor(src: Any, code: int, dst: Any = ..., dstCn: int = ...) -> Any: ...
def imshow(winname: str, mat: Any) -> None: ...
def waitKey(delay: int = ...) -> int: ...
def destroyAllWindows() -> None: ...

class VideoCapture:
    def __init__(self, source: Union[str, int]) -> None: ...
    def isOpened(self) -> bool: ...
    def read(self) -> Tuple[bool, Any]: ...
    def release(self) -> None: ...

# --- SIFT / FLANN (image_matcher.py) ---
def SIFT_create(nfeatures: int = ..., nOctaveLayers: int = ..., contrastThreshold: float = ..., edgeThreshold: float = ..., sigma: float = ...) -> Any: ...

class FlannBasedMatcher:
    def __init__(self, indexParams: Dict[str, Any], searchParams: Dict[str, Any]) -> None: ...
    def knnMatch(
        self,
        queryDescriptors: Any,
        trainDescriptors: Any,
        k: int,
        mask: Any = ...,
        compactResult: bool = ...,
    ) -> List[List[Any]]: ...
